### ISSUE TITLE
Move to Browserslist org

### ISSUE THREAD

**Issue by ai** [browserslist/browserslist-rs#10]
Do you want to move your repo to Browserslist, org? It will show an official level of your amazing project?

You will be still main maintainer and I will ask only for queries compatibility (which is already OK).

**Comment by g-plane** [comment]
Sorry for delay.

It sounds OK, and can I also join the [Browserslist](https://github.com/browserslist) organization?

**Comment by ai** [comment]
> Can I also join the [Browserslist](https://github.com/browserslist) organization?

Of course! I already sent you an invite.

After you accept an invitation you will have an ability to move repo.

**Comment by g-plane** [comment]
It's moved.

**Comment by ai** [comment]
Welcome to the team =^_^=
