### ISSUE TITLE
Does `target.'cfg(target = "wasm32-unknown-unknown")'.dependencies` work?

### ISSUE THREAD

**Issue by kdy1** [browserslist/browserslist-rs#12]
Context: https://github.com/nextest-rs/nextest/issues/499

The author said 

> I checked and target is definitely not supported by Cargo -- it always evaluates to false

So I'm not sure if it's working.
[The official cargo doc](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#platform-specific-dependencies) 

If it's working, I'll reopen the issue above

**Comment by g-plane** [comment]
Do you mean whether it can run as WebAssembly or not?

**Comment by kdy1** [comment]
I mean, is `it always evaluates to false` true?

`@swc/wasm` is using it, so I think it works with Wasm but it causes a problem with `cargo nextest`

**Comment by g-plane** [comment]
It shouldn't be if targeting WebAssembly.

**Comment by g-plane** [comment]
After reading Cargo docs, it seems that the predicate is wrong. I'll fix it later.

**Comment by kdy1** [comment]
Thank you!
