### ISSUE TITLE
Using newer chrono features without depending on a new enough chrono

### ISSUE THREAD

**Issue by tv42** [browserslist/browserslist-rs#14]
You're using `Utc.with_ymd_and_hms` https://github.com/browserslist/browserslist-rs/blob/1abf8eeb95516442b73b86ffaaacbae22ae0b085/src/queries/since.rs#L10

while depending on just Chrono >=0.4 https://github.com/browserslist/browserslist-rs/blob/1abf8eeb95516442b73b86ffaaacbae22ae0b085/Cargo.toml#L55

but that method was added relatively recently on Nov 9 https://github.com/chronotope/chrono/commit/7ba090d484cb93f73e5a7803dd62e4c4295f3b50 and is only included in chrono 0.4.23 and newer.

**Comment by g-plane** [comment]
It sounds that I should specify the accurate version, right?

**Comment by tv42** [comment]
Yeah just bump it to 0.4.23 in Cargo..toml
