### ISSUE TITLE
Switch from chrono to time >=0.3

### ISSUE THREAD

**Issue by tv42** [browserslist/browserslist-rs#16]
`cargo deny check` complains about a potential segfault, due to `chrono` using an old version of `time`: https://rustsec.org/advisories/RUSTSEC-2020-0071

The best fix is to stop using `chrono`, and use newer `time`: https://github.com/chronotope/chrono/issues/602#issuecomment-940218484

**Comment by g-plane** [comment]
As the comment says, it's unaffected. And, I found chrono v0.5.x (not released yet) removes `time`, so I think we can wait for that release.

**Comment by tv42** [comment]
It's unaffected, but that's not reflected in the machine-readable data -> `cargo deny` warns about this.

**Comment by g-plane** [comment]
`time` is removed from `chrono` v0.4.30, and we're using v0.4.31, so we close this now.
