### ISSUE TITLE
List of supported browsers?

### ISSUE THREAD

**Issue by patricklafrance** [browserslist/browserslist-rs#20]
I am implementing a function to convert browserslist results to SWC targets, similar to https://github.com/marcofugaro/browserslist-to-esbuild/tree/main. I keep getting error messages like the following:

```
thread '<unnamed>' panicked at 'not implemented: Targets: {"bb": Query(Single("7")), "ie": Query(Single("5.5")), "edge": Query(Single("106")), "firefox": Query(Single("107")), "opera": Query(Single("92")), "android": Query(Single("115")), "chrome": Query(Single("107")), "samsung": Query(Single("12")), "safari": Query(Single("15.2"))}', C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\preset_env_base-0.4.5\src\query.rs:124:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
assets by status 1.1 KiB [cached] 2 assets
./src/index.ts 39 bytes [built] [code generated] [1 error]
```

I get these error messages from SWC but from my understanding SWC is delegating this to browserslist-rs.

I was wondering what targets does browserlist-rs support? 

For example, "baidu", "kaios" and "bb" seems to be supported by the original browserslist tool but not by browserlist-rs.

Thank you!

Patrick

**Comment by g-plane** [comment]
Look at this function: https://github.com/browserslist/browserslist-rs/blob/99a3244fc8c0e631a80a9cae5c41dca6c5a2aae5/build.rs#L10 .

**Comment by patricklafrance** [comment]
Thank you for the quick answer, appreciated 🙏🏻 

My issue seems to be that my test data is requesting a version that is too low, like `bb 7`.

**Comment by patricklafrance** [comment]
I hope it's fine if I ask here @g-plane, instead of SWC. I noticed that you are a contributor to both projects.

Do you have any idea why when I provide a target to SWC for any of the following browsers: "ios_saf", "op_mini", "bb", "ie_mob", "and_uc", "and_qq", "baidu", "kaios"

I get an error similar to this?

`ERROR in ./src/index.ts
Module build failed (from ./node_modules/.pnpm/swc-loader@0.2.3_@swc+core@1.3.78_webpack@5.88.2/node_modules/swc-loader/src/index.js):
Error: failed to handle: not implemented: Targets: {"samsung": Query(Single("12")), "edge": Query(Single("106")), "kaios": Query(Single("2.5")), "and_qq": Query(Single("13.1")), "ie_mob": Query(Single("10")), "op_mob": Query(Single("73")), "chrome": Query(Single("107")), "safari": Query(Single("15.2")), "opera": Query(Single("92")), "and_ff": Query(Single("115")), "and_uc": Query(Single("15.5")), "ie": Query(Single("5.5")), "and_chr": Query(Single("115")), "baidu": Query(Single("13.18")), "bb": Query(Single("7")), "firefox": Query(Single("107")), "ios_saf": Query(Single("15.2")), "android": Query(Single("115")), "op_mini": Query(Single("all"))}`

According to this list: [browserslist-rs/build.rs](https://github.com/browserslist/browserslist-rs/blob/99a3244fc8c0e631a80a9cae5c41dca6c5a2aae5/build.rs#L10) they are supported by browserslist-rs.

Thank you,

Patrick

**Comment by g-plane** [comment]
If you've installed Rust development environment, you can clone this repository and check your query with the command below:

```
cargo run --example inspect -- <query>
```

If it outputs result successfully, it means "browserslist-rs" works, then you need to consult SWC because they do additional transformations.
