### ISSUE TITLE
Switching to std::lazylock in v0.16.1 breaks min-rust and therefore semver 

### ISSUE THREAD

**Issue by jkelleyrtp** [browserslist/browserslist-rs#26]
Hello,

Dioxus is running into CI failures since the patch release of 0.16.1 switches to a rust feature that was once unstable.

It is invalid to bump min-rust requirements in a patch release.

https://doc.rust-lang.org/cargo/reference/semver.html#env-new-rust

v0.16.1 should be yanked and re-published under v0.17.0

**Comment by g-plane** [comment]
v0.17.0 is released. Sorry for the breaking.
